name: SAST Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"  # Wekelijkse scan op zondag

permissions:
  contents: read
  security-events: write  # Nodig voor CodeQL

jobs:
  sast-analysis:
    runs-on: ubuntu-latest

    steps:
    # Stap 1: Haal de code op
    - name: Checkout code
      uses: actions/checkout@v4

    # Stap 2: Initialiseer CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    # Stap 3: Voer CodeQL-analyse uit
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
