name: Full Secrets Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  secrets-scan:
    name: Full Repository Secrets Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      # Step 2: Run TruffleHog to scan entire repository
      - name: TruffleHog OSS - Full Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./  # Scan all files in the repository
          extra_args: --debug  # Output debug information for troubleshooting

      # Step 3: Fail the workflow if secrets are found
      - name: Fail on secrets detection
        if: failure() || cancelled()
        run: exit 1
