name: Secrets Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Run TruffleHog
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./  # Scan the entire repository
          extra_args: --debug  # Debug mode to see more logs

      # Step 3: Fail workflow if secrets are found
      - name: Fail on secrets detection
        if: failure()
        run: exit 1
