name: Secrets Detection

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"  # Weekly scan on Sundays at midnight

permissions:
  contents: read

jobs:
  secrets-scan:
    name: Check for Hardcoded Secrets
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Run TruffleHog to detect secrets
    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@v4
      with:
        # Scans the entire repository
        scan-all-files: true

    # Optional: Fail the workflow on secrets detection
    - name: Fail if secrets detected
      if: failure()
      run: exit 1
